group: lock: use group path instead of debug for error message
this changes the error from:

  Error: while creating locked backup group 'BackupGroup { store: "store", ns: BackupNamespace { inner: ["namespace"], len: 6 }, group: BackupGroup { ty: Host, id: "group" } }'

to

  Error: while creating locked backup group "/store/pbs/ns/namespace/host/group"'

Signed-off-by: Fabian Grünbichler <f.gruenbichler@proxmox.com>
Link: https://lore.proxmox.com/20260428110259.766084-1-f.gruenbichler@proxmox.com