group: lock: inline error instead of using context
all the other errors here are constructed like this, and call sites do not log
the context yet, so the error is incomplete otherwise..

this changes the error for concurrent group/snapshot creation from:

  Error: while creating locked backup group "/store/pbs/ns/namespace/host/group"'

to:

  Error: unable to acquire backup group lock "/run/proxmox-backup/locks/store/namespace/host-group" while creating locked backup group "/store/pbs/ns/namespace/host/group"

Signed-off-by: Fabian Grünbichler <f.gruenbichler@proxmox.com>
Link: https://lore.proxmox.com/20260428110259.766084-2-f.gruenbichler@proxmox.com